### ISSUE TITLE
TypeError: can't convert Symbol into String

### ISSUE THREAD

**Issue by Naatan** [Aupajo/middleman-search_engine_sitemap#4]
All I did was install the addon and activate it, no special settings.

```
TypeError: can't convert Symbol into String
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:5:in `join'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:5:in `block (4 levels) in singletonclass'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:4:in `block (3 levels) in singletonclass'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:3:in `each'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:3:in `block (2 levels) in singletonclass'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:2:in `block in singletonclass'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:65533:in `instance_eval'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:65533:in `singletonclass'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-search_engine_sitemap-1.3.0/lib/middleman/search_engine_sitemap/templates/sitemap.xml.builder:65531:in `__tilt_30944680'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/tilt-1.4.1/lib/tilt/builder.rb:20:in `evaluate'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/rendering.rb:303:in `render_individual_file'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/rendering.rb:181:in `_render_with_all_renderers'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/rendering.rb:149:in `render_template'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/sitemap/resource.rb:127:in `block in render'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/activesupport-4.1.9/lib/active_support/notifications.rb:161:in `instrument'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/util.rb:41:in `instrument'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/application.rb:219:in `instrument'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/sitemap/resource.rb:14:in `instrument'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/sitemap/resource.rb:100:in `render'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:256:in `process_request'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:206:in `block in call!'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:205:in `catch'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:205:in `call!'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:191:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-livereload-0.3.15/lib/rack/livereload.rb:23:in `_call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-livereload-0.3.15/lib/rack/livereload.rb:14:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
	/home/nathan/.rvm/gems/ruby-1.9.3-p547/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/home/nathan/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
	/home/nathan/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
	/home/nathan/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

**Comment by Naatan** [comment]
Found the issue - my url_root was malformed.
